# Generated by Django 4.2.1 on 2023-05-22 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='shortly_description',
            field=models.TextField(default=1, max_length=200, verbose_name='qisqacha izoh'),
            preserve_default=False,
        ),
    ]
