# Generated by Django 4.2.1 on 2023-05-24 10:47

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_and_tuiters', '0002_alter_beststudent_shortly_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=30, verbose_name='Familya')),
                ('status', models.CharField(default='Yordamchi', max_length=50, verbose_name='Vazifasi')),
                ('shortly_description', models.TextField(max_length=250, verbose_name='qisqacha izoh')),
                ('image', models.ImageField(upload_to='media_members/', verbose_name='rasm')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Media A'zosi",
                'verbose_name_plural': "Media A'zolari",
                'ordering': ['created_at'],
            },
        ),
    ]
